embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
learning_rate: [0.0005]
reg_weight: [0.001]
dropout: [0.5]
walk_length: [50]
ssl_temp: [0.2]
ssl_weight: [0,0.02,0.04,0.06,0.08,0.1]
choosing_tmp: [0.2]





hyper_parameters: ["reg_weight", "learning_rate","walk_length","ssl_temp","choosing_tmp","ssl_weight"]