embedding_size: 64
feat_embed_dim: 64

n_mm_layers: 1
n_layers: 2
knn_k: 10
mm_image_weight: 0.1
learning_rate: 0.001
reg_weight: [0.001]

dropout: [0.5]
image_knn_k: [10]
text_knn_k: [10]
temp: 0.2 
aug_lambda: 0.05

mi_weight: 0.01




hyper_parameters: ["reg_weight","image_knn_k","text_knn_k","vt_weight","fused_weight"]