# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization
import dgl
import dgl.function as fn
import torch
import torch.nn as nn
import torch.nn.functional as F
import copy
from utils.utils import * 
from utils.fusion import CrossModalAttention 



class INFOMGF2(GeneralRecommender):
    def __init__(self, config, dataset):
        super(INFOMGF2, self).__init__(config, dataset)
        import ipdb; ipdb.set_trace()
        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.embedding_size = config['embedding_size']
        self.feat_embed_dim = config['embedding_size']
        self.n_layers = config['n_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = 'add'
        self.dataset = dataset
        self.dropout = config['dropout']
        self.reg_weight = config['reg_weight']

        self.temp = config['temp']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None

        
        
        self.id_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.mm_adj = None
        self.t_preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(self.n_users, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
        self.v_preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(self.n_users, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))


        


        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        # self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']),
        #                                allow_pickle=True).item()

        

        if self.v_feat is not None:
            # self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            # self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

       


        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)
        self.item_index = torch.zeros([self.num_item], dtype=torch.long)


        if self.v_feat is not None:
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device)

        if self.t_feat is not None:
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device)



        self.result_embed = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(num_user + num_item, dim_x)))).to(self.device)
        
        self.image_knn_k = config['image_knn_k']
        self.text_knn_k = config['text_knn_k']
        self.sparse = True
    
        image_adj_file = os.path.join(dataset_path, 'image_adj_{}_{}.pt'.format(self.image_knn_k, self.sparse))
        text_adj_file = os.path.join(dataset_path, 'text_adj_{}_{}.pt'.format(self.text_knn_k, self.sparse))
        if os.path.exists(image_adj_file):
                image_adj = torch.load(image_adj_file)
        else:
            image_adj = build_sim(self.v_feat.detach())
            image_adj = build_knn_normalized_graph(image_adj, topk=self.image_knn_k, is_sparse=self.sparse,
                                                    norm_type='sym')
            torch.save(image_adj, image_adj_file)
        self.image_original_adj = image_adj.to(self.device) 
        
        if os.path.exists(text_adj_file):
                text_adj = torch.load(text_adj_file)
        else:
            text_adj = build_sim(self.t_feat.detach())
            text_adj = build_knn_normalized_graph(text_adj, topk=self.text_knn_k, is_sparse=self.sparse, norm_type='sym')
            torch.save(text_adj, text_adj_file)
        self.text_original_adj = text_adj.to(self.device)
        self.fusion_adj = max_pool_fusion(self.image_original_adj,self.text_original_adj,device=self.device) 
        self.mm_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=128,
                             device=self.device)
        
        self.temp = config['temp']
        self.mi_weight = config['mi_weight']
   
        # self.mlp = nn.Linear(self.embedding_size*2,self.embedding_size)
        # self.proj_fused =nn.Sequential(
        #             nn.Linear(self.embedding_size * 2, self.embedding_size),
        #             nn.ReLU(inplace=True),
        #             nn.Linear(self.embedding_size, self.embedding_size)
        #         )
    
        
        self.Fusion_Layer = CrossModalAttention(self.embedding_size)
        self.aug_lambda = config['aug_lambda']
        self.edge_aug = Discriminator(self.embedding_size,self.embedding_size,aug_lambda=self.aug_lambda)
        # self.weight_u = nn.Parameter(torch.randn(self.num_user, 2))
        # self.weight_u.data = F.softmax(self.weight_u, dim=1)
        # self.tau1 = 0.025
        # self.tau2= 0.025


    def get_adj_mat(self):
        adj_mat = sp.dok_matrix((self.n_users + self.n_items, self.n_users + self.n_items), dtype=np.float32)
        adj_mat = adj_mat.tolil()
        R = self.interaction_matrix.tolil()

        adj_mat[:self.n_users, self.n_users:] = R
        adj_mat[self.n_users:, :self.n_users] = R.T
        adj_mat = adj_mat.todok()

        def normalized_adj_single(adj):
            rowsum = np.array(adj.sum(1))
            rowsum[rowsum == 0] = 1  # 避免除0错误
            
            d_inv = np.power(rowsum, -0.5).flatten()
            d_inv[np.isinf(d_inv)] = 0.
            d_mat_inv = sp.diags(d_inv)

            norm_adj = d_mat_inv.dot(adj_mat)
            norm_adj = norm_adj.dot(d_mat_inv)
            return norm_adj.tocoo()

        norm_adj_mat = normalized_adj_single(adj_mat)
        norm_adj_mat = norm_adj_mat.tolil()
        self.R = norm_adj_mat[:self.n_users, self.n_users:]
        return norm_adj_mat.tocsr()

    def sparse_mx_to_torch_sparse_tensor(self, sparse_mx):
        """Convert a scipy sparse matrix to a torch sparse tensor."""
        sparse_mx = sparse_mx.tocoo().astype(np.float32)
        indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
        values = torch.from_numpy(sparse_mx.data)
        shape = torch.Size(sparse_mx.shape)
        return torch.sparse.FloatTensor(indices, values, shape)
    
    def pack_item_edge_index(self):
        edge_src = [] 
        edge_dst = [] 
        edge_weights = []
        for item_id,(nbr_list,w_list) in self.item_graph_dict.items():
            for nbr_id,w in zip(nbr_list,w_list):
                edge_src.append(item_id)
                edge_dst.append(nbr_id)
                edge_weights.append(w)
                edge_src.append(nbr_id)
                edge_dst.append(item_id)
                edge_weights.append(w)
        edge_index = torch.tensor([edge_src, edge_dst], dtype=torch.long)
        edge_weight = torch.tensor(edge_weights, dtype=torch.float)

        return edge_index, edge_weight

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        pass

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def InfoNCE(self, view1, view2, index,temp=0.2,):
        view1, view2 = F.normalize(view1[index], dim=1), F.normalize(view2[index], dim=1)
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        ttl_score = torch.matmul(view1, view2.transpose(0, 1))
        ttl_score = torch.exp(ttl_score / temp).sum(dim=1)
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)
    def InfoNCE_decoder(self, view1, view2, temp=0.2):
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        ttl_score = torch.matmul(view1, view2.transpose(0, 1))
        ttl_score = torch.exp(ttl_score / temp).sum(dim=1)
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)

    def forward(self):
        
        ## MLP and Cross Modal Attention 

        # t_feat_ori = self.text_trs(self.t_feat)
        v_feat_ori = self.image_trs(self.v_feat)
        # fused_feat_ori = self.Fusion_Layer(t_feat_ori,v_feat_ori)
        # fused_preference = self.Fusion_Layer(self.t_preference,self.v_preference)
        
        ## Item Item Graph 
        # t_feat = torch.sparse.mm(self.text_original_adj,t_feat_ori)
        v_feat = torch.sparse.mm(self.image_original_adj,v_feat_ori)
        # fused_feat = torch.sparse.mm(self.fusion_adj,fused_feat_ori)
        
        
        
        # self.t_rep = self.t_gcn(self.edge_index,self.t_preference,t_feat) 
     
        self.v_rep = self.v_gcn(self.edge_index,self.v_preference,v_feat)
        
        self.edge_weight = self.edge_aug(self.v_rep,self.edge_index)
        self.v_rep_aug = self.v_gcn(self.edge_index,self.v_preference,v_feat,edge_weight=self.edge_weight)
    
        
        # self.fused_rep = self.mm_gcn(self.edge_index,fused_preference,fused_feat)
        
        
        # self.t_user,self.t_item = torch.split(self.t_rep,[self.n_users,self.n_items],dim=0)
        # self.v_user,self.v_item = torch.split(self.v_rep,[self.n_users,self.n_items],dim=0)
        # self.fused_item = torch.cat([self.t_item,self.v_item],dim=1)
        # self.fused_user = torch.cat([self.t_user,self.v_user],dim=1)
        
        
        # self.t_item = self.t_item + torch.sparse.mm(self.text_original_adj,self.t_item)
        # self.v_item = self.v_item + torch.sparse.mm(self.image_original_adj,self.v_item)
        # self.fused_item = self.fused_item +  torch.sparse.mm(self.fusion_adj,self.fused_item)

        # weighted_t = self.t_user*self.weight_u[:self.num_user, 0:1]
        # weighted_v = self.v_user*self.weight_u[:self.num_user, 1:2] 
        # self.fused_user = torch.cat([weighted_v, weighted_t], dim=1)
        

        # self.t_rep = torch.cat([self.t_user,self.t_item],dim=0)
        # self.v_rep = torch.cat([self.v_user,self.v_item],dim=0)
        # self.fused_rep =  torch.cat([self.fused_user,self.fused_item],dim=0)
        
        
        
        
        
        
        
        # self.fusion_rep = self.mm_gcn(self.edge_index,x_fusion)
        
        # representation = torch.cat((self.v_rep,self.t_rep),dim=1) 
  

    

        self.result_embed = self.v_rep 

       
        return None

    def buildItemGraph(self, h):

        h = torch.sparse.mm(self.mm_adj, h)
        return h
   

    def BPR(self,result_embed):
        user_tensor = result_embed[self.user_nodes]
        pos_item_tensor = result_embed[self.pos_item_nodes]
        neg_item_tensor = result_embed[self.neg_item_nodes]

        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        loss_rec = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        return loss_rec
    
    
    def calculate_loss(self, interaction):
        self.user_nodes, self.pos_item_nodes, self.neg_item_nodes = interaction[0], interaction[1], interaction[2]
        self.pos_item_nodes += self.n_users
        self.neg_item_nodes += self.n_users
        
        self.forward()
        ## Rec loss 
        # loss_rec_fused = self.BPR(self.result_embed)
        # loss_rec_v = self.BPR(self.v_rep)
        # loss_rec_t = self.BPR(self.t_rep) 
        # loss_rec = loss_rec_fused+loss_rec_t+loss_rec_v
        loss_rec_v  = self.BPR(self.v_rep)
        loss_rec_aug = self.BPR(self.v_rep_aug)
    
        loss_rec = loss_rec_v + loss_rec_aug 
    
        
        ## InforNCE
        loss_ssl_user = self.InfoNCE(self.v_rep,self.v_rep_aug,self.user_nodes)
        loss_ssl_item = self.InfoNCE(self.v_rep,self.v_rep_aug,self.pos_item_nodes)
        loss_ssl = self.ssl_weight*(loss_ssl_user+loss_ssl_item)
        
        
        
        
     

        reg_embedding_loss_t = (self.t_preference[self.user_nodes] ** 2).mean() if self.t_preference is not None else 0.0
        reg_embedding_loss_v = (self.v_preference[self.user_nodes] ** 2).mean() if self.v_preference is not None else 0.0
       
        reg_loss = self.reg_weight * (reg_embedding_loss_t+reg_embedding_loss_v)
  
  
    
        return loss_rec + reg_loss + loss_ssl

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix


    
   





        

from sklearn.preprocessing import StandardScaler
class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode,
                 dim_latent=None, device=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = dim_latent
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.device = device
        if self.dim_latent:

            self.conv_embed = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.conv_embed = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self,edge_index, prefer,feature,edge_weight=None):
        
        x = torch.cat([prefer,feature],dim=0)
        x = F.normalize(x)
        
        # item -> user  
        h = self.conv_embed(x, edge_index,edge_weight)
        # user MLP 
        
        h_1 = self.conv_embed(h,edge_index,edge_weight)
        x_hat = x + h + h_1 
        return x_hat
    


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index,edge_weight=None,size=None):
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        

        return self.propagate(edge_index, edge_weight=edge_weight,size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j,edge_index,edge_weight=None, size=None):
        if self.aggr == 'add':
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            if edge_weight is not None: 
                return norm.view(-1,1)*edge_weight.view(-1,1)*x_j  
            else:
                return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)
    

class Discriminator(nn.Module):
    def __init__(self, input_dim, out_dim, aug_lambda, temperature=1.0, bias=0.0 + 0.0001):
        super(Discriminator, self).__init__()

        self.edge_mlp = nn.Sequential(nn.Linear(input_dim* 2, 1))

        self.temperature = temperature
        self.bias = bias
        self.aug_lambda = aug_lambda

        self.decoder = nn.Sequential(nn.Linear(out_dim, input_dim))

 

    def get_edge_weight(self, embeddings, edges):
        s1 = self.edge_mlp(torch.cat((embeddings[edges[0]], embeddings[edges[1]]), dim=1)).flatten()
        s2 = self.edge_mlp(torch.cat((embeddings[edges[1]], embeddings[edges[0]]), dim=1)).flatten()
        return (s1 + s2) / 2

    def gumbel_sampling(self, edges_weights_raw):
        eps = (self.bias - (1 - self.bias)) * torch.rand(edges_weights_raw.size()) + (1 - self.bias)
        gate_inputs = torch.log(eps) - torch.log(1 - eps)
        gate_inputs = gate_inputs.to(edges_weights_raw.device)
        gate_inputs = (gate_inputs + edges_weights_raw) / self.temperature
        output = torch.sigmoid(gate_inputs).squeeze()

        return output

    def forward(self, embedding, edges):
        edges_weights_raw = self.get_edge_weight(embedding, edges)
        weights = self.gumbel_sampling(edges_weights_raw)
        return weights

    # def cal_loss_dis(self, z_aug_adjs, z_specific_adjs, view_features):

    #     loss_upmi = 0
    #     loss_rec = 0
    #     batch_size, _ = z_specific_adjs[0].size()
    #     pos_eye = torch.eye(batch_size).to(z_specific_adjs[0].device)
    #     for i in range(len(z_specific_adjs)):
    #         loss_upmi += self.aug_lambda * calc_upper_bound(z_aug_adjs[i], z_specific_adjs[i], pos_eye)
    #         # 最小化增广图的表征和特殊表征的互信息
    #         feat_agg_rec = self.decoder(z_aug_adjs[i])
    #         loss_rec += sce_loss(feat_agg_rec, view_features[i])
    #         # 最小化重构损失,要求增广图和原始图保持一致性 

    #     loss_dis = loss_upmi + loss_rec
    #     return loss_dis

