# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization

import torch
import torch.nn as nn
import torch.nn.functional as F
import copy

from torch_cluster import random_walk
import torch_sparse

class CGI(GeneralRecommender):
    def __init__(self, config, dataset):
        super(CGI, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.embedding_size = config['feat_embed_dim']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = 'add'
        self.dataset = dataset
        self.dropout = config['dropout']
        self.reg_weight = config['reg_weight']

        self.temp = config['temp']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None

        
        
        self.id_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.mm_adj = None
        self.t_prefer = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(self.n_users, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))

        


        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']),
                                       allow_pickle=True).item()

        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # if self.v_feat is not None:
        #     self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
        #     self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if os.path.exists(mm_adj_file):
            self.mm_adj = torch.load(mm_adj_file)
        else:
            if self.v_feat is not None:
                indices, image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
                self.mm_adj = image_adj
            if self.t_feat is not None:
                indices, text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
                self.mm_adj = text_adj
            if self.v_feat is not None and self.t_feat is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
                del text_adj
                del image_adj
            torch.save(self.mm_adj, mm_adj_file)

        self.walk_length = config['walk_length']
        self.ssl_temp = config['ssl_temp']
        self.choosing_tmp = config['choosing_tmp']
        self.ssl_weight = config['ssl_weight']
        self.interaction_matrix  = dataset.inter_matrix(form='coo').astype(np.float32)
        self.create_sparse_adjaceny() 
        self.edge_mask_learner = nn.ModuleList([nn.Sequential(nn.Linear(2 * self.embedding_size, self.embedding_size), nn.ReLU(), nn.Linear(self.embedding_size, 1)) for i in range(self.n_layers)])
        



        self.result_embed = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(self.n_users + self.n_items, dim_x)))).to(self.device)

    def pack_item_edge_index(self):
        edge_src = [] 
        edge_dst = [] 
        edge_weights = []
        for item_id,(nbr_list,w_list) in self.item_graph_dict.items():
            for nbr_id,w in zip(nbr_list,w_list):
                edge_src.append(item_id)
                edge_dst.append(nbr_id)
                edge_weights.append(w)
                edge_src.append(nbr_id)
                edge_dst.append(item_id)
                edge_weights.append(w)
        edge_index = torch.tensor([edge_src, edge_dst], dtype=torch.long)
        edge_weight = torch.tensor(edge_weights, dtype=torch.float)

        return edge_index, edge_weight

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        pass

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def InfoNCE(self, view1, view2, temp):
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        ttl_score = torch.matmul(view1, view2.transpose(0, 1))
        ttl_score = torch.exp(ttl_score / temp).sum(dim=1)
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)

    def forward(self, interaction):
    
        edge_mask_list = [] 
   
        
        t_feat = self.text_trs(self.t_feat)
        x_t= torch.cat((self.t_preference,t_feat),dim=0) 
        x_t = F.normalize(x_t) 
        
        cur_embedding = x_t 
        all_embeddings = [cur_embedding]
        edge_mask_list = [] 
        node_mask_list = [] 
        
        for i in range(self.n_layers):
            cur_embedding = torch.mm(self.norm_adj, cur_embedding)
            all_embeddings.append(cur_embedding)

            # edge_num * 2emebdding_size
            edge_cat_embedding = torch.cat([cur_embedding[self.row], cur_embedding[self.col]], dim=-1)
            edge_mask = self.edge_mask_learner[i](edge_cat_embedding)
            bias = 0.0 + 0.0001  # If bias is 0, we run into problems
            eps = (bias - (1 - bias)) * torch.rand(edge_mask.size()) + (1 - bias)
            edge_gate_inputs = torch.log(eps) - torch.log(1 - eps)
            edge_gate_inputs = edge_gate_inputs.to(self.device)
            edge_gate_inputs = (edge_gate_inputs + edge_mask) / self.choosing_tmp
            edge_mask = torch.sigmoid(edge_gate_inputs).squeeze(1)
            edge_mask_list.append(edge_mask)

        all_embeddings = torch.stack(all_embeddings, dim=0)
        all_embeddings = torch.sum(all_embeddings, dim=0, keepdim=False)
        user_rep, item_rep = torch.split(all_embeddings, [self.n_users,self.n_items])

        # edge_dropout_view##################
        
        cur_embedding_edge_drop =  x_t
        all_embeddings_edge_drop = [cur_embedding_edge_drop]

        # # edge_reg = 0
        for i in range(self.n_layers):
            edge_mask = edge_mask_list[i]
            new_edge = torch.mul(self.norm_adj.values(), edge_mask)
            # edge_reg += new_edge.sum()/len(self.interact_matrix)

            cur_embedding_edge_drop = torch_sparse.spmm(self.norm_adj.indices(), new_edge, self.n_users + self.n_items, self.n_users + self.n_items, cur_embedding_edge_drop)
            all_embeddings_edge_drop.append(cur_embedding_edge_drop)

        all_embeddings_edge_drop = torch.stack(all_embeddings_edge_drop, dim=0)
        all_embeddings_edge_drop = torch.sum(all_embeddings_edge_drop, dim=0, keepdim=False)
        user_rep_edge_drop, item_rep_edge_drop = torch.split(all_embeddings_edge_drop, [self.n_users,self.n_items])  

        # edge_reg = edge_reg / self.n_layers

        # build result embedding

        self.result_embed = torch.cat((user_rep, item_rep), dim=0)
        self.result_embed_ED = torch.cat((user_rep_edge_drop,item_rep_edge_drop))
        
        # calculate pos and neg scores
        
        return self.result_embed,self.result_embed_ED

    def buildItemGraph(self, h):
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return h


    def calculate_loss(self, interaction):
       
        users, pos_items, neg_items = interaction[0], interaction[1], interaction[2]
        pos_items += self.n_users
        neg_items += self.n_users
        pos_items = pos_items.to(self.device)
        neg_items = neg_items.to(self.device)
        
        result_embed,result_embed_ED = self.forward(interaction)
        # result_embed = self.forward(interaction)
        ## Rec Loss 
        user_tensor = result_embed[users]
        pos_item_tensor = result_embed[pos_items]
        neg_item_tensor = result_embed[neg_items]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        loss_rec = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        
        # ## Rec Loss ED 
        user_tensor_ED = result_embed_ED[users]
        pos_item_tensor_ED = result_embed_ED[pos_items]
        neg_item_tensor_ED = result_embed_ED[neg_items]
        pos_scores_ED = torch.sum(user_tensor_ED * pos_item_tensor_ED, dim=1)
        neg_scores_ED = torch.sum(user_tensor_ED * neg_item_tensor_ED, dim=1)
        loss_rec_ED = -torch.mean(torch.log2(torch.sigmoid(pos_scores_ED - neg_scores_ED)))
        ## SSL loss 
        def ssl_compute(x1, x2):
            # batch_size
            x1 = F.normalize(x1)
            x2 = F.normalize(x2)
            pos_score = torch.sum(torch.mul(x1, x2), dim=1, keepdim=False)
            # batch_size * batch_size
            all_score = torch.mm(x1, x2.t())
            ssl_mi = torch.log(torch.exp(pos_score/self.ssl_temp) / torch.exp(all_score/self.ssl_temp).sum(dim=1, keepdim=False)).mean()
            return ssl_mi
        
        loss_user_edge = ssl_compute(user_tensor_ED,user_tensor)
        loss_item_edge = ssl_compute(pos_item_tensor_ED,pos_item_tensor)
        
        
        
        # loss_recon = self.sce_loss(v_mask,v_recon)+self.sce_loss(t_mask,t_recon)

        reg_embedding_loss_t = (self.t_preference[users] ** 2).mean() if self.t_preference is not None else 0.0
        reg_loss = self.reg_weight * (reg_embedding_loss_t)
        
        loss = loss_rec_ED + loss_rec + self.ssl_weight * (loss_user_edge+loss_item_edge)+reg_loss
        
        return loss 

    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]
        user_tensor_ED = self.result_embed_ED[:self.n_users]
        item_tensor_ED = self.result_embed_ED[self.n_users:]
        

        temp_user_tensor = user_tensor[interaction[0], :]
        temp_user_tensor_ED = user_tensor_ED[interaction[0],:]
        
        user_embed = torch.cat((temp_user_tensor,temp_user_tensor_ED),dim = -1)
        item_embed = torch.cat((item_tensor,item_tensor_ED),dim=-1)
        
        score_matrix = torch.matmul(user_embed,item_embed.t())
        
        return score_matrix

    def print_embd(self):
        return self.result_embed_v, self.result_embed_t
    
    def mask_noise(self,x,mask_token,mask_rate=0.1):
      
        perm = torch.randperm(self.n_items, device=x.device)
        num_mask_items = int(mask_rate*self.n_items)
        mask_items = perm[:num_mask_items]
        keep_items = perm[num_mask_items]
        mask_x = x.clone()
        token_nodes = mask_items.clone()
        mask_x[mask_items] = 0 
        mask_x[token_nodes] += mask_token

        
        return  mask_x,mask_items,keep_items
    def get_adj_mat(self):
        adj_mat = sp.dok_matrix((self.n_users + self.n_items, self.n_users + self.n_items), dtype=np.float32)
        adj_mat = adj_mat.tolil()
        R = self.interaction_matrix.tolil()

        adj_mat[:self.n_users, self.n_users:] = R
        adj_mat[self.n_users:, :self.n_users] = R.T
        adj_mat = adj_mat.todok()

        def normalized_adj_single(adj):
            rowsum = np.array(adj.sum(1))
            rowsum[rowsum == 0] = 1  # 避免除0错误
            
            d_inv = np.power(rowsum, -0.5).flatten()
            d_inv[np.isinf(d_inv)] = 0.
            d_mat_inv = sp.diags(d_inv)

            norm_adj = d_mat_inv.dot(adj_mat)
            norm_adj = norm_adj.dot(d_mat_inv)
            return norm_adj.tocoo()

        norm_adj_mat = normalized_adj_single(adj_mat)
        norm_adj_mat = norm_adj_mat.tolil()
        self.R = norm_adj_mat[:self.n_users, self.n_users:]
        return norm_adj_mat.tocsr()
    def create_sparse_adjaceny(self):
        """
        复现 create_sparse_adjaceny 的邻接矩阵构造方法
        """
        # 直接从 interaction_matrix 提取 COO 格式的索引和值
        coo_matrix = self.interaction_matrix.tocoo()
        self.row = torch.from_numpy(coo_matrix.row).long()
        self.col = torch.from_numpy(coo_matrix.col).long()
        values = torch.from_numpy(coo_matrix.data).float()

        # 交互矩阵 (user_num, item_num) 的 PyTorch 版本
        self.interact_matrix = torch.sparse_coo_tensor(
            indices=torch.stack([self.row, self.col]), values=values, 
            size=(self.n_users, self.n_items)
        )

        # 构造完整的邻接矩阵 (user_num + item_num, user_num + item_num)
        tmp_row = self.row
        tmp_col = self.col + self.n_users  # 物品索引整体右移 self.n_users
        tmp_values = values.clone()  # 复制 values 避免修改

        tmp_adj = torch.sparse_coo_tensor(
            indices=torch.stack([tmp_row, tmp_col]), values=tmp_values, 
            size=(self.n_users + self.n_items, self.n_users + self.n_items)
        )

        # 计算对称邻接矩阵 A + A^T
        self.joint_adjaceny_matrix = (tmp_adj + tmp_adj.t()).coalesce()

        # 计算度矩阵 D
        degree = torch.sparse.sum(self.joint_adjaceny_matrix, dim=1).to_dense()
        degree = torch.pow(degree, -0.5)
        degree[torch.isinf(degree)] = 0  # 避免无穷大的问题
        D_inverse = torch.diag(degree).to_sparse()

        # 计算对称归一化邻接矩阵 D^(-1/2) * A * D^(-1/2)
        self.norm_adj = torch.sparse.mm(
            torch.sparse.mm(D_inverse, self.joint_adjaceny_matrix), D_inverse
        ).coalesce()

        # 生成随机游走邻接矩阵
        joint_indices = self.norm_adj.indices()
        self.row = joint_indices[0]
        self.col = joint_indices[1]
        
        # 生成随机游走路径
        start = torch.arange(self.n_users + self.n_items)
        walk = random_walk(self.row, self.col, start, walk_length=self.walk_length)

        # 构造随机游走邻接矩阵
        self.rw_adj = torch.zeros((self.n_users + self.n_items, self.n_users + self.n_items))
        self.rw_adj = torch.scatter(self.rw_adj, 1, walk, 1).to_sparse()

        # 计算随机游走归一化
        degree = torch.sparse.sum(self.rw_adj, dim=1).to_dense()
        degree = torch.pow(degree, -1)
        degree[torch.isinf(degree)] = 0
        D_inverse = torch.diag(degree).to_sparse()
        self.rw_adj = torch.sparse.mm(D_inverse, self.rw_adj).to(self.device)

        # 确保所有计算的矩阵移动到 GPU
        self.norm_adj = self.norm_adj.to(self.device)
        
    def sparse_mx_to_torch_sparse_tensor(self, sparse_mx):
        """Convert a scipy sparse matrix to a torch sparse tensor."""
        sparse_mx = sparse_mx.tocoo().astype(np.float32)
        indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
        values = torch.from_numpy(sparse_mx.data)
        shape = torch.Size(sparse_mx.shape)
        return torch.sparse.FloatTensor(indices, values, shape)
    
    
        
        


