# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py

"""
扩散之后采用向量量化,控制模态共因

"""


import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric
from diffusion.diffusion_v1 import diffusion
from utils.graphmlp import GMLP

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization


import torch
import torch.nn as nn
import torch.nn.functional as F
import copy
from utils.utils import * 
from utils.fusion import CrossModalAttention 
from utils.loss import * 
import torch_sparse
from torch_cluster import random_walk

class VQ_VER1_BABY(GeneralRecommender):
    def __init__(self, config, dataset):
        super(VQ_VER1_BABY, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items

        dim_x = config['embedding_size']
        self.embedding_size = config['feat_embed_dim']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']
        self.dropout = config['dropout']
        self.reg_weight = config['reg_weight']
        self.temp = config['temp']
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.image_knn_k = config['image_knn_k']
        self.text_knn_k = config['text_knn_k']
        self.diff_weight = config['diff_weight']
        self.steps = config['timesteps']
        self.choosing_tmp = config['choosing_tmp']
        self.walk_length = config['walk_length']
        self.ssl_weight = config['ssl_weight']
        self.w1 = config['w1']
        self.w2 = config['w2']
        

        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = 'add'
        self.dataset = dataset
        

        
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None

        
        
        self.id_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.mm_adj = None
        self.t_prefer = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(self.n_users, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
        self.v_prefer= nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(self.n_users, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))


        if self.v_feat is not None:
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

   
        self.interaction_matrix  = dataset.inter_matrix(form='coo').astype(np.float32)
        self.create_sparse_adjaceny()
  
    
        
        self.sparse = True
    
        image_adj_file = os.path.join(dataset_path, 'image_adj_{}_{}.pt'.format(self.image_knn_k, self.sparse))
        text_adj_file = os.path.join(dataset_path, 'text_adj_{}_{}.pt'.format(self.text_knn_k, self.sparse))
        if os.path.exists(image_adj_file):
                image_adj = torch.load(image_adj_file)
        else:
            image_adj = build_sim(self.v_feat.detach())
            image_adj = build_knn_normalized_graph(image_adj, topk=self.image_knn_k, is_sparse=self.sparse,
                                                    norm_type='sym')
            torch.save(image_adj, image_adj_file)
        self.image_original_adj = image_adj.to(self.device) 
        
        if os.path.exists(text_adj_file):
                text_adj = torch.load(text_adj_file)
        else:
            text_adj = build_sim(self.t_feat.detach())
            text_adj = build_knn_normalized_graph(text_adj, topk=self.text_knn_k, is_sparse=self.sparse, norm_type='sym')
            torch.save(text_adj, text_adj_file)
        self.text_original_adj = text_adj.to(self.device)
        
        
        
        self.fused_adj = max_pool_fusion(self.image_original_adj,self.text_original_adj,device=self.device) 
  

        self.diffusion_tgv = diffusion(config)
        self.diffusion_vgt = diffusion(config)
        self.num_envs = config["num_envs"]
        self.env_dim = config["env_dim"]
        self.env_proj_t = nn.Linear(self.embedding_size,self.env_dim)
        self.env_proj_v = nn.Linear(self.embedding_size,self.env_dim)
        self.codebook_t = EnvEmbedding(self.num_envs,self.env_dim)
        self.codebook_v = EnvEmbedding(self.num_envs,self.env_dim)
        self.t_proj = nn.Linear(self.env_dim,self.embedding_size)
        self.v_proj = nn.Linear(self.env_dim,self.embedding_size)
        
        

        
        self.sample_t = None
        self.sample_v = None
        self.vq_weight = config['vq_weight']
        self.beta = config['beta']
        
        
        self.text_graphlearner = nn.ModuleList([nn.Sequential(nn.Linear(2 * self.embedding_size, self.embedding_size), nn.ReLU(), nn.Linear(self.embedding_size, 1)) for i in range(self.n_layers)])
        self.image_graphlearner = nn.ModuleList([nn.Sequential(nn.Linear(2 * self.embedding_size, self.embedding_size), nn.ReLU(), nn.Linear(self.embedding_size, 1)) for i in range(self.n_layers)])
        
        self.construction = config['construction']

    
    def create_sparse_adjaceny(self):
        """
        复现 create_sparse_adjaceny 的邻接矩阵构造方法
        """
        # 直接从 interaction_matrix 提取 COO 格式的索引和值
        coo_matrix = self.interaction_matrix.tocoo()
        self.row = torch.from_numpy(coo_matrix.row).long()
        self.col = torch.from_numpy(coo_matrix.col).long()
        values = torch.from_numpy(coo_matrix.data).float()

        # 交互矩阵 (user_num, item_num) 的 PyTorch 版本
        self.interact_matrix = torch.sparse_coo_tensor(
            indices=torch.stack([self.row, self.col]), values=values, 
            size=(self.n_users, self.n_items)
        )

        # 构造完整的邻接矩阵 (user_num + item_num, user_num + item_num)
        tmp_row = self.row
        tmp_col = self.col + self.n_users  
        tmp_values = values.clone() 

        tmp_adj = torch.sparse_coo_tensor(
            indices=torch.stack([tmp_row, tmp_col]), values=tmp_values, 
            size=(self.n_users + self.n_items, self.n_users + self.n_items)
        )

        self.joint_adjaceny_matrix = (tmp_adj + tmp_adj.t()).coalesce()

        # 计算度矩阵 D
        degree = torch.sparse.sum(self.joint_adjaceny_matrix, dim=1).to_dense()
        degree = torch.pow(degree, -0.5)
        degree[torch.isinf(degree)] = 0  # 避免无穷大的问题
        D_inverse = torch.diag(degree).to_sparse()

        # 计算对称归一化邻接矩阵 D^(-1/2) * A * D^(-1/2)
        self.norm_adj = torch.sparse.mm(
            torch.sparse.mm(D_inverse, self.joint_adjaceny_matrix), D_inverse
        ).coalesce()

        # 生成随机游走邻接矩阵
        joint_indices = self.norm_adj.indices()
        self.row = joint_indices[0]
        self.col = joint_indices[1]
        
        # 生成随机游走路径
        start = torch.arange(self.n_users + self.n_items)
        walk = random_walk(self.row, self.col, start, walk_length=self.walk_length)

        # 构造随机游走邻接矩阵
        self.rw_adj = torch.zeros((self.n_users + self.n_items, self.n_users + self.n_items))
        self.rw_adj = torch.scatter(self.rw_adj, 1, walk, 1).to_sparse()

        # 计算随机游走归一化
        degree = torch.sparse.sum(self.rw_adj, dim=1).to_dense()
        degree = torch.pow(degree, -1)
        degree[torch.isinf(degree)] = 0
        D_inverse = torch.diag(degree).to_sparse()
        self.rw_adj = torch.sparse.mm(D_inverse, self.rw_adj).to(self.device)

        # 确保所有计算的矩阵移动到 GPU
        self.norm_adj = self.norm_adj.to(self.device)
  

    def drop_edges(self,edge_index, drop_rate=0.2):
        """
        随机丢弃一定比例的边
        :param edge_index: [2, num_edges] 的张量，表示图的边
        :param drop_rate: 丢弃边的比例
        :return: 新的 edge_index
        """
        num_edges = edge_index.size(1)  # 获取边的数量
        keep_prob = 1 - drop_rate  # 需要保留的比例

        mask = torch.rand(num_edges, device=edge_index.device) < keep_prob

        # 只保留 mask 选中的边
        edge_index = edge_index[:, mask]
        return edge_index
    
    def get_adj_mat(self):
        adj_mat = sp.dok_matrix((self.n_users + self.n_items, self.n_users + self.n_items), dtype=np.float32)
        adj_mat = adj_mat.tolil()
        R = self.interaction_matrix.tolil()

        adj_mat[:self.n_users, self.n_users:] = R
        adj_mat[self.n_users:, :self.n_users] = R.T
        adj_mat = adj_mat.todok()

        def normalized_adj_single(adj):
            rowsum = np.array(adj.sum(1))
            rowsum[rowsum == 0] = 1  # 避免除0错误
            
            d_inv = np.power(rowsum, -0.5).flatten()
            d_inv[np.isinf(d_inv)] = 0.
            d_mat_inv = sp.diags(d_inv)

            norm_adj = d_mat_inv.dot(adj_mat)
            norm_adj = norm_adj.dot(d_mat_inv)
            return norm_adj.tocoo()

        norm_adj_mat = normalized_adj_single(adj_mat)
        norm_adj_mat = norm_adj_mat.tolil()
        self.R = norm_adj_mat[:self.n_users, self.n_users:]
        return norm_adj_mat.tocsr()

    def sparse_mx_to_torch_sparse_tensor(self, sparse_mx):
        """Convert a scipy sparse matrix to a torch sparse tensor."""
        sparse_mx = sparse_mx.tocoo().astype(np.float32)
        indices = torch.from_numpy(np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
        values = torch.from_numpy(sparse_mx.data)
        shape = torch.Size(sparse_mx.shape)
        return torch.sparse.FloatTensor(indices, values, shape)
    
    def pack_item_edge_index(self):
        edge_src = [] 
        edge_dst = [] 
        edge_weights = []
        for item_id,(nbr_list,w_list) in self.item_graph_dict.items():
            for nbr_id,w in zip(nbr_list,w_list):
                edge_src.append(item_id)
                edge_dst.append(nbr_id)
                edge_weights.append(w)
                edge_src.append(nbr_id)
                edge_dst.append(item_id)
                edge_weights.append(w)
        edge_index = torch.tensor([edge_src, edge_dst], dtype=torch.long)
        edge_weight = torch.tensor(edge_weights, dtype=torch.float)

        return edge_index, edge_weight

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        pass

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        return np.column_stack((rows, cols))

    def InfoNCE_base(self, view1, view2, index,temp=0.2):
        view1 = view1[index]
        view2 = view2[index]
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        ttl_score = torch.matmul(view1, view2.transpose(0, 1))
        ttl_score = torch.exp(ttl_score / temp).sum(dim=1)
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)
    def InfoNCE(self,view1,view2,temp=0.2):
        loss_user = self.InfoNCE_base(view1,view2,self.user_nodes)
        loss_item = self.InfoNCE_base(view1,view2,self.pos_item_nodes)
        return loss_user+loss_item 

    

    def forward(self,t_unigraph,v_unigraph,t_common,v_common):
        t_embedding = self.w1 * t_common + (1-self.w1)* t_unigraph
        v_embedding = self.w2 * v_common + (1-self.w2)* v_unigraph 
        self.t_rep,self.t_aug = self.aug(self.t_prefer,t_embedding,self.text_graphlearner)
        self.v_rep,self.v_aug = self.aug(self.v_prefer,v_embedding,self.image_graphlearner)
        self.result_embed = self.t_rep
        if self.construction == 'cat':
            self.result_embed = torch.cat((self.t_rep,self.v_rep),dim=1)
        elif self.construction == 'only_text':
            self.result_embed = self.t_rep
        elif self.construction == 'only_image':
            self.result_embed = self.v_rep


        return None


    
    def aug(self,user_prefer,item_feat,graph_learner):
        x = torch.cat((user_prefer,item_feat),dim=0)
        x = F.normalize(x)
        cur_embedding = x
        all_embeddings = [cur_embedding]
        edge_mask_list = []
        for i in range(self.n_layers):
            cur_embedding = torch.mm(self.norm_adj, cur_embedding)
            all_embeddings.append(cur_embedding)
            edge_embedding = torch.cat([cur_embedding[self.row], cur_embedding[self.col]], dim=-1)
            edge_mask = graph_learner[i](edge_embedding)
            bias = 0.0 + 0.0001
            eps = (bias - (1 - bias)) * torch.rand(edge_mask.size()) + (1 - bias)
            edge_gate_inputs = torch.log(eps) - torch.log(1 - eps)
            edge_gate_inputs = edge_gate_inputs.to(self.device)
            edge_gate_inputs = (edge_gate_inputs + edge_mask) / self.choosing_tmp
            edge_mask = torch.sigmoid(edge_gate_inputs).squeeze(1)
            edge_mask_list.append(edge_mask)
        all_embeddings = torch.stack(all_embeddings, dim=0)
        all_embeddings = torch.sum(all_embeddings, dim=0, keepdim=False)
        
        cur_embedding_edge_drop =  x.clone()
        all_embeddings_edge_drop = [cur_embedding_edge_drop]
        for i in range(self.n_layers):
            edge_mask = edge_mask_list[i]
            new_edge = torch.mul(self.norm_adj.values(), edge_mask)
            cur_embedding_edge_drop = torch_sparse.spmm(self.norm_adj.indices(), new_edge, self.n_users + self.n_items, self.n_users + self.n_items, cur_embedding_edge_drop)
            all_embeddings_edge_drop.append(cur_embedding_edge_drop)

        all_embeddings_edge_drop = torch.stack(all_embeddings_edge_drop, dim=0)
        all_embeddings_edge_drop = torch.sum(all_embeddings_edge_drop, dim=0, keepdim=False)
        
        return all_embeddings,all_embeddings_edge_drop
        
    def buildItemGraph(self, h):
        h = torch.sparse.mm(self.mm_adj, h)
        return h
   

    def BPR(self,result_embed):
        user_tensor = result_embed[self.user_nodes]
        pos_item_tensor = result_embed[self.pos_item_nodes]
        neg_item_tensor = result_embed[self.neg_item_nodes]
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        loss_rec = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        return loss_rec
    def VectorLoss(self,t_in,t_q,v_in,v_q):

        v_in = torch.cat((v_in[self.pos_item],v_in[self.neg_item]),dim=0)
        t_in = torch.cat((t_in[self.pos_item],t_in[self.neg_item]),dim=0)
        v_q = torch.cat((v_q[self.pos_item],v_q[self.neg_item]),dim=0)
        t_q = torch.cat((t_q[self.pos_item],t_q[self.neg_item]),dim=0)
        
        loss_vq_v = F.mse_loss(v_in,v_q) + self.beta * F.mse_loss(v_q,v_in)
        loss_vq_t = F.mse_loss(t_in,t_q) + self.beta * F.mse_loss(t_q,t_in)
        return loss_vq_t + loss_vq_v
        
        
    
    def calculate_loss(self, interaction):
        self.user_nodes, self.pos_item_nodes, self.neg_item_nodes = interaction[0], interaction[1], interaction[2]
        self.pos_item = self.pos_item_nodes.clone() 
        self.neg_item = self.neg_item_nodes.clone()
        self.pos_item_nodes += self.n_users
        self.neg_item_nodes += self.n_users
        
        t_feat_ori = self.text_trs(self.t_feat)
        v_feat_ori = self.image_trs(self.v_feat)
        t_unigrpah = torch.sparse.mm(self.text_original_adj,t_feat_ori)
        v_unigraph = torch.sparse.mm(self.image_original_adj,v_feat_ori)
        
        t= torch.randint(low=0, high=self.steps, size=(t_feat_ori.shape[0] // 2 + 1,)).to(self.device)
        t = torch.cat([t, self.steps - t - 1], dim=0)[:t_feat_ori.shape[0]]
        
      
        diff_loss1,v_common = self.diffusion_tgv.p_losses(v_unigraph,t_feat_ori,t) 
        diff_loss2,t_common = self.diffusion_vgt.p_losses(t_unigrpah,v_feat_ori,t)
        diff_loss = self.diff_weight*(diff_loss1+diff_loss2)
        t_in = self.env_proj_t(t_common)
        v_in = self.env_proj_v(v_common)
        v_output, v_q, v_ind = self.codebook_v.straight_through(v_in)
        t_output, t_q, t_ind = self.codebook_t.straight_through(t_in)
        loss_vq = self.vq_weight * self.VectorLoss(t_in,t_q,v_in,v_q)
        v_common = self.v_proj(v_output)
        t_common = self.t_proj(t_output)
        self.forward(t_unigrpah,v_unigraph,t_common,v_common)
        loss_rec_main = self.BPR(self.t_rep) + self.BPR(self.v_rep)
        loss_rec_aug = self.BPR(self.t_aug) + self.BPR(self.v_aug)

        loss_rec = loss_rec_main + loss_rec_aug 


        reg_embedding_loss_v = (self.v_prefer[self.user_nodes] ** 2).mean() if self.v_prefer is not None else 0.0
        reg_embedding_loss_t = (self.t_prefer[self.user_nodes] ** 2).mean() if self.t_prefer is not None else 0.0
        reg_loss = self.reg_weight * (reg_embedding_loss_v+reg_embedding_loss_t) 
  
        ssl_loss_t_aug = self.InfoNCE(self.t_rep,self.t_aug)
        ssl_loss_v_aug = self.InfoNCE(self.v_rep,self.v_aug)
        
        ssl_loss = self.ssl_weight * (ssl_loss_t_aug + ssl_loss_v_aug) 
  

        return loss_rec + reg_loss + ssl_loss + diff_loss + loss_vq

    def full_sort_predict(self, interaction):
        t_feat_ori = self.text_trs(self.t_feat)
        v_feat_ori = self.image_trs(self.v_feat)
        t_unigrpah = torch.sparse.mm(self.text_original_adj,t_feat_ori)
        v_unigraph = torch.sparse.mm(self.image_original_adj,v_feat_ori)

        self.forward(t_unigrpah,v_unigraph,self.sample_t,self.sample_v)
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]
        
        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix
    
    def sample(self):
        t_feat_ori = self.text_trs(self.t_feat)
        v_feat_ori = self.image_trs(self.v_feat)
        t_unigrpah = torch.sparse.mm(self.text_original_adj,t_feat_ori)
        v_unigraph = torch.sparse.mm(self.image_original_adj,v_feat_ori)
        
        v_common = self.diffusion_tgv.sample(v_unigraph,t_feat_ori) 
        t_common = self.diffusion_vgt.sample(t_unigrpah,v_feat_ori)
        v_in = self.env_proj_v(v_common)
        t_in = self.env_proj_t(t_common)
        v_output, v_q, v_ind = self.codebook_v.straight_through_test(v_in)
        t_output, t_q, t_ind = self.codebook_t.straight_through_test(t_in)
        v_common = self.v_proj(v_output)
        t_common = self.t_proj(t_output)
        
        self.sample_t = t_common.detach()
        self.sample_v= v_common.detach()





  
  


    

class EnvEmbedding(nn.Module):
    def __init__(self, K, D):
        super().__init__()
        # 初始化代码本（codebook）层，K为环境的数量，D为环境向量的维度
        self.embedding = nn.Embedding(K, D)  
        # 初始化权重为均匀分布的值
        self.embedding.weight.data.uniform_(-1./K, 1./K)

    def forward(self, x):
    
        x_ = x.contiguous()  
        latents = vq(x_, self.embedding.weight)
        return latents  

    def straight_through(self, z_e_x):  # x: [b, h_d]，即批次大小b，潜在向量维度h_d
    
        '''
        z_e_x: 代表环境的潜在向量
        '''
  
        #z_e_x.shape:torch.Size([32, 140])
        z_e_x_ = z_e_x.contiguous()  # 确保z_e_x是连续存储的
        # 使用vq_st函数进行straight-through估计，得到离散化的潜在向量和对应的索引
        z_q_x_, indices = vq_st(z_e_x_, self.embedding.weight.detach())  # z_q_x_: 离散化的潜在表示,torch.Size([32, 140]);indices: 对应的索引,torch.Size([32])
        z_q_x = z_q_x_.contiguous()  # 保证z_q_x是连续的

        # 从embedding表中选择与索引对应的向量
        z_q_x_bar_flatten = torch.index_select(self.embedding.weight, dim=0, index=indices) # torch.Size([32, 140])
        z_q_x_bar_ = z_q_x_bar_flatten.view_as(z_e_x_)  # 恢复形状
        z_q_x_bar = z_q_x_bar_.contiguous()  # 保证是连续存储

        return z_q_x, z_q_x_bar, indices  # 返回离散化的潜在向量、量化的向量以及索引

    def straight_through_test(self, z_e_x):  # 当进行soft index的测试时
        '''
        这个函数执行soft索引操作，即不进行硬选择
        '''

        inputs = z_e_x.contiguous()  # 确保输入是连续存储的
        codebook = self.embedding.weight.detach()  # 从codebook中获取环境向量，detach表示不参与梯度计算

        with torch.no_grad():  # 不需要计算梯度
            embedding_size = codebook.size(1)  # 获取embedding的维度
            inputs_flatten = inputs.view(-1, embedding_size)  # 将输入展平
            codebook_sqr = torch.sum(codebook ** 2, dim=1)  # 计算codebook中每个向量的平方和
            inputs_sqr = torch.sum(inputs_flatten ** 2, dim=1, keepdim=True)  # 计算输入向量的平方和
            # 计算输入向量与codebook中所有向量的欧几里得距离
            distances = torch.addmm(codebook_sqr + inputs_sqr, inputs_flatten, codebook.t(), alpha=-2.0, beta=1.0)
            # 使用softmax计算距离的概率分布（得到索引）
            indices = torch.softmax(distances, dim=1)  
            # 计算soft索引对应的环境向量
            codes_flatten = torch.mm(indices, codebook)
            codes = codes_flatten.view_as(inputs)  # 恢复到原来的形状

            return codes.contiguous(), None, indices  # 返回soft索引对应的环境向量和对应的索引


import torch
from torch.autograd import Function
class VectorQuantization(Function):
    @staticmethod
    def forward(ctx, inputs, codebook):

        with torch.no_grad():
            embedding_size = codebook.size(1)
            inputs_size = inputs.size()
            inputs_flatten = inputs.view(-1, embedding_size)

            codebook_sqr = torch.sum(codebook ** 2, dim=1)
            inputs_sqr = torch.sum(inputs_flatten ** 2, dim=1, keepdim=True)

            # Compute the distances to the codebook
            distances = torch.addmm(codebook_sqr + inputs_sqr,
                inputs_flatten, codebook.t(), alpha=-2.0, beta=1.0)

            _, indices_flatten = torch.min(distances, dim=1)
            indices = indices_flatten.view(*inputs_size[:-1])
            ctx.mark_non_differentiable(indices)

            return indices

    @staticmethod
    def backward(ctx, grad_output):
        raise RuntimeError('Trying to call `.grad()` on graph containing '
            '`VectorQuantization`. The function `VectorQuantization` '
            'is not differentiable. Use `VectorQuantizationStraightThrough` '
            'if you want a straight-through estimator of the gradient.')

class VectorQuantizationStraightThrough(Function):
    @staticmethod
    def forward(ctx, inputs, codebook):
 
        indices = vq(inputs, codebook)
        indices_flatten = indices.view(-1)
        ctx.save_for_backward(indices_flatten, codebook)
        ctx.mark_non_differentiable(indices_flatten)

        codes_flatten = torch.index_select(codebook, dim=0,
            index=indices_flatten)
        codes = codes_flatten.view_as(inputs)

        return (codes, indices_flatten)

    @staticmethod
    def backward(ctx, grad_output, grad_indices):
 
        grad_inputs, grad_codebook = None, None

        if ctx.needs_input_grad[0]:
            # Straight-through estimator
            grad_inputs = grad_output.clone()
        if ctx.needs_input_grad[1]:
            # Gradient wrt. the codebook
            indices, codebook = ctx.saved_tensors
            embedding_size = codebook.size(1)

            grad_output_flatten = (grad_output.contiguous()
                                              .view(-1, embedding_size))
            grad_codebook = torch.zeros_like(codebook)
            grad_codebook.index_add_(0, indices, grad_output_flatten)

        return (grad_inputs, grad_codebook)

vq = VectorQuantization.apply
vq_st = VectorQuantizationStraightThrough.apply
__all__ = [vq, vq_st]